'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, GraduationCap, Search } from 'lucide-react';
import { airlines } from '@/lib/airlines';
import { AirlineMark } from './ui';
export function Perks() {
  const [filter, setFilter] = useState('');
  const programs = airlines.filter(a => a.student && (a.name + ' ' + a.student.name).toLowerCase().includes(filter.toLowerCase()));
  return <div className="container perks-page"><div className="perks-page-heading"><div><div className="eyebrow">YOUR STUDENT ID. YOUR POSSIBILITIES.</div><h1>A little extra<br /><em>for the journey.</em></h1><p>Some airlines offer student fares, more baggage or flexible tickets. Find their programs here, then let the airline confirm what applies to you.</p></div><span className="perks-page-icon"><GraduationCap size={85} strokeWidth={1.2} /></span></div><div className="perks-explainer"><GraduationCap size={24} /><p><strong>Check the offer before you book.</strong> These links help you discover programs. Current terms haven’t been independently verified; no age eligibility, discount or extra baggage is guaranteed or added to flight results.</p></div><div className="program-toolbar"><h2>Airline student programs</h2><label><Search size={17} /><input aria-label="Find an airline student program" placeholder="Find an airline…" value={filter} onChange={e => setFilter(e.target.value)} /></label></div><div className="program-grid">{programs.map(a => <article className="program-card" key={a.code}><div className="program-airline"><AirlineMark airline={a} /><h3>{a.name}</h3></div><span className="program-type">{a.student!.name}</span><p>{a.student!.description}</p><span className="terms-status"><span />Current terms need review</span><a href={a.student!.url} target="_blank" rel="noopener noreferrer" className="program-link">Explore on the airline’s site<ArrowUpRight size={17} /></a></article>)}</div>{programs.length === 0 && <div className="results-empty"><h2>No program matches “{filter}”.</h2><button className="text-button" onClick={() => setFilter('')}>Show all programs</button></div>}<div className="perks-bottom"><div><h2>Your next chapter is waiting.</h2><p>Find a flight, then check student offers with your chosen airline.</p></div><a className="button" href="/#search">Find a flight<ArrowRight size={17} /></a></div></div>;
}
