'use client';
import { useState } from 'react';
import { ArrowUpRight, GraduationCap, Info, Luggage } from 'lucide-react';
import { money } from '@/lib/search';
import { studentComparison } from '@/lib/student-value';
import type { FlightOffer, SearchQuery } from '@/lib/types';
import { Modal } from './ui';

export function StudentOverview({ offers, query, scores, onSelect }: { offers: FlightOffer[]; query: SearchQuery; scores: Map<string, number>; onSelect: (offer: FlightOffer) => void }) {
  const [guide, setGuide] = useState(false);
  const example = offers.every(o => o.mode === 'demo');
  return <section className="student-overview" aria-label="Compare student flight value">
    <div className="student-overview-heading"><div><span className="eyebrow"><GraduationCap size={18} />YOUR STUDENT ID CHANGES THE COMPARISON</span><h2>Compare your student advantage.</h2><p>The fare is only the start. Compare baggage and total cost per adult.</p></div><span className="baggage-target"><Luggage size={17} />You need <strong>{query.baggage} kg</strong></span></div>
    <div className="comparison-table-scroll" tabIndex={0} role="region" aria-label="Scrollable student comparison table"><table className="comparison-table"><caption className="sr-only">{example ? 'Illustrative' : 'Flight'} comparison per adult for {query.baggage} kg checked baggage</caption><thead><tr><th scope="col">Airline / fare</th><th scope="col">Standard</th><th scope="col">Student extra</th><th scope="col">Total if eligible</th><th scope="col">Cost with {query.baggage} kg</th><th scope="col">Student value</th></tr></thead><tbody>{offers.map(offer => {
      const c = studentComparison(offer, query);
      const score = scores.get(offer.id);
      return <tr key={offer.id}><th scope="row"><button onClick={() => onSelect(offer)} aria-label={'View ' + offer.airlineName + ' itinerary'}>{offer.airlineName}<ArrowUpRight size={12} /></button><span>{money(offer.price / offer.passengers, offer.currency)} fare</span></th><td>{c.standardKg === undefined ? 'See bag details' : c.standardKg + ' kg'}</td><td className={c.extraKg && c.extraKg > 0 ? 'comparison-bonus' : ''}>{c.extraKg === undefined ? 'Unverified' : c.extraKg > 0 ? '+' + c.extraKg + ' kg' : 'No extra'}{c.example && <small>example</small>}</td><td><strong>{c.eligibleKg === undefined ? 'To confirm' : c.eligibleKg + ' kg'}</strong><small>{c.eligibleKg !== undefined && c.eligibleKg >= query.baggage ? 'Fits your bags' : 'Check allowance'}</small></td><td><strong>{c.comparableCostPerAdult === undefined ? 'To confirm' : money(c.comparableCostPerAdult, offer.currency)}</strong><small>{c.additionalCostPerAdult === undefined ? 'Add-on not quoted' : c.additionalCostPerAdult > 0 ? '+' + money(c.additionalCostPerAdult, offer.currency) + ' baggage' : 'No bag top-up'}</small></td><td><span className="table-value-score">{score === undefined ? 'Pending' : score.toFixed(1) + '/10'}</span></td></tr>;
    })}</tbody></table></div>
    <div className="overview-footnote"><p><Info size={14} />{example ? 'Preview comparison: student extras and bag add-on prices are fictional, not airline policies.' : 'Student benefits need official verification. Unverified extras are not added to your baggage or fare.'}</p><button className="text-button" onClick={() => setGuide(true)}>How student value works</button></div>
    {guide && <Modal title="How student value works" onClose={() => setGuide(false)}><div className="value-guide"><p>We compare the cost of meeting your baggage needs, the baggage included before paid add-ons, and the combined travel time of your outbound and return flights.</p><div className="score-weights"><div><strong>40%</strong><span>Cost with your bags</span></div><div><strong>45%</strong><span>Included baggage fit</span></div><div><strong>15%</strong><span>Total travel time</span></div></div><p>Price and time are measured against the lowest comparable cost and shortest trip in the search. Baggage coverage is capped at your requested weight. The weighted result is shown out of 10; filters do not change the score.</p><p>Prices are per adult. An extra baggage package is counted as many times as needed to cover a shortfall. These example add-on quotes cover the complete itinerary. The base ticket price is unchanged.</p><p>Scores stay pending when eligible baggage or the required add-on price is unknown, or when currencies differ. A pending score is not a poor score.</p><div className="guide-example"><GraduationCap size={20} /><p><strong>Examples are for the preview only.</strong> Demo bonuses and add-on costs are fictional. Live and sandbox results never use them. Confirm age, enrollment, route, fare and registration eligibility with the airline.</p></div></div></Modal>}
  </section>;
}
